# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systemUsersForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import *


class systemUsersForm(QWidget):
    def __init__(self):
        super(systemUsersForm, self).__init__()
        self.initUI()

    def initUI(self):
        self.setWindowTitle('系统用户管理')
        self.resize(800, 600)
        layout = QFormLayout()

        self.labId = QLabel('Id')
        self.lineId = QLineEdit()
        self.labName = QLabel('姓名')
        self.lineName = QLineEdit()
        self.labGender = QLabel('性别')
        self.lineGender = QLineEdit()

        self.btnSave = QPushButton('保存')
        self.btnExit = QPushButton('退出')

        layout.addRow(self.labId, self.lineId)
        layout.addRow(self.labName, self.lineName)
        layout.addRow(self.labGender, self.lineGender)
        layout.addRow(self.btnSave, self.btnExit)

        self.setLayout(layout)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    main = systemUsersForm()
    main.show()
    sys.exit(app.exec_())
